export PAGER="/bin/sh -c \"unset PAGER;col -b -x | vim -R -c 'set ft=man nomod nolist' -c 'set nu!' -c 'map q :q<CR>' -c 'map <SPACE> <C-D>' -c 'map b <C-U>' -c 'nmap K :Man <C-R>=expand(\\\"<cword>\\\")<CR><CR>' -\""

if [ "$PS1" ]; then
    PS1="\n\[$(tput bold)$(tput setaf 2)\]\u@\h: \[$(tput setaf 4)\]\w\[$(tput sgr0)\] \$ "
    PS1="\[\e]0;\u@\h\a\]$PS1"
fi

if [ -d $HOME/computing ]; then
    PATH=$PATH:$HOME/computing/bin
fi
